#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  \#353535
bspc config focused_border_color \#AAAAAA
bspc config border_width		 1

panel &
compton --config /home/benjc/.config/compton.conf &

xrdb -load .Xresources

feh --bg-scale ~/Media/green-forest-floor-1920x1200.jpg
xsetroot -cursor_name left_ptr
