#!/usr/bin/env zsh

sxhkd &

if [[ -n "$MON_1" ]]; then
    xrandr --output "$MON_1" --rotate left --right-of "$MON_0"
    [[ "$MON_1" == DP1 ]] && xrandr --output "$MON_1" --scale 1.4
	bspc monitor "$MON_1" -d 6 7 8 9 10
	bspc monitor -d 1 2 3 4 5
	TERMINAL_DESKTOP=6
	BROWSER_DESKTOP=1
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
	TERMINAL_DESKTOP=1
	BROWSER_DESKTOP=2
fi

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  \#353535
bspc config focused_border_color \#AAAAAA
bspc config border_width		 1

# Sys

"$HOME/.config/polybar/launch.sh" &
compton --config "$HOME/.config/compton.conf" &

xrdb -load ~/.Xresources

feh --bg-scale /usr/share/backgrounds/gnome/Fabric.jpg
xsetroot -cursor_name left_ptr

hash libinput-gestures-setup && libinput-gestures-setup restart &

hash ckb-next && /usr/bin/ckb-next --background &

### User

bspc desktop ^$TERMINAL_DESKTOP -l monocle
bspc desktop ^$BROWSER_DESKTOP -l monocle

bspc desktop --focus ^$TERMINAL_DESKTOP && kitty & sleep 1
bspc desktop --focus ^$BROWSER_DESKTOP && firefox &

sleep 3 && bspc desktop --focus ^$TERMINAL_DESKTOP

bspc desktop --focus ^$(( TERMINAL_DESKTOP + 1 )) && firefox & sleep 1

bspc desktop --focus ^$TERMINAL_DESKTOP
