#!/usr/bin/env zsh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  \#353535
bspc config focused_border_color \#555577
bspc config border_width     1

"$HOME/.config/polybar/launch.sh" &
# compton --config ~/.config/compton.conf  --backend glx &

xrdb -load ~/.Xresources
feh --bg-scale "$HOME/Pictures/wallpaper-space.jpg"
xsetroot -cursor_name left_ptr

hash libinput-gestures-setup && libinput-gestures-setup restart &
# hash ckb-next && (sleep 7 && /usr/bin/ckb-next --background) &
