[metadata]
name = "kanagawa_dragon"
author = "Tommaso Laurenzi"
origin_url = "https://github.com/revelot/kanagawa.nvim"

[colors]
background = "#181616"
foreground = "#c5c9c5"
selection_bg = "#223b4e"
# selection_fg = "#c8c093"
split = "#181616"
cursor_fg = "#c8c093"

ansi = [
  "#0d0c0c",
  "#c4746e",
  "#8a9a7b",
  "#c4b28a",
  "#8ba4b0",
  "#a292a3",
  "#8ea4a2",
  "#c8c093",
]

brights = [
  "#a6a69c",
  "#e46876",
  "#87a987",
  "#e6c384",
  "#7fb4ca",
  "#938aa9",
  "#7aa89f",
  "#c5c9c5",
]

[colors.indexed]
16 = "#b6927b"
17 = "#b98d7b"

[colors.tab_bar]
background = "#0c0c0c"
inactive_tab_edge = "#0c0c0c"
inactive_tab_edge_hover = "#252525"

[colors.tab_bar.active_tab]
bg_color = "#12120f"
fg_color = "#c8c093"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#12120f"
fg_color = "#a6a69c"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"
