[metadata]
name = "kanagawa_dragon"
author = "Tommaso Laurenzi"
origin_url = "https://github.com/revelot/kanagawa.nvim"

[colors]
background = "#1F1F28"
foreground = "#DCD7BA"
selection_bg = "#2A2A37"
# selection_fg = "#C8C093"
split = "#1F1F28"
cursor_fg = "#C8C093"

ansi = [
  "#16161D",
  "#C34043",
  "#76946A",
  "#C0A36E",
  "#7E9CD8",
  "#957FB8",
  "#6A9589",
  "#C8C093",
]

brights = [
  "#727169",
  "#E82424",
  "#98BB6C",
  "#E6C384",
  "#7FB4CA",
  "#938AA9",
  "#7AA89F",
  "#DCD7BA",
]

[colors.indexed]
16 = "#FFA066"
17 = "#FF5D62"

[colors.tab_bar]
background = "#1F1F28"
inactive_tab_edge = "#1F1F28"
inactive_tab_edge_hover = "#2A2A37"

[colors.tab_bar.active_tab]
bg_color = "#2A2A37"
fg_color = "#C8C093"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1F1F28"
fg_color = "#727169"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#1F1F28"
fg_color = "#727169"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#2A2A37"
fg_color = "#727169"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#2A2A37"
fg_color = "#727169"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"
