#!/usr/bin/env bash

rofi -m eDP1 -no-lazy-grab -show drun \
	-drun-display-format "  {name}" \
	-display-drun "Search" \
	-hide-scrollbar true \
	-lines 11 \
	-line-padding 10 \
	-border-raduis 20 \
	-width 15 \
	-xoffset 10 -yoffset -40 \
	-location 7 \
	-columns 1 \
	-show-icons -icon-theme "Papirus" \
	-font "Noto Sans 11"
