#!/bin/bash

SESSION=`basename $PWD`
tmux -2 new-session -d -s ${SESSION}

# Window 1
tmux rename-window -t ${SESSION}:1 general-purpose 
# Window 2
tmux new-window -t ${SESSION} -a -n git # -a: next index
tmux split-window -h
tmux select-pane -t 0
# Window 3
tmux new-window -t ${SESSION} -a -n vim # -a: next index
tmux split-window -h
tmux select-pane -t 0
tmux resize-pane -R 40

tmux send-keys -t ${SESS_NAME}:3.0 'vim ~/Dropbox/MSc/Modules/' Enter 
tmux send-keys -t ${SESS_NAME}:3.1 'cd ~/Dropbox/MSc/Modules/' Enter

tmux select-window -t ${SESSION}:1
tmux -2 attach -t ${SESSION}
