#!/bin/zsh

SESS_NAME="GeneralUse"

tmux has-session -t ${SESS_NAME}

if [ $? != 0 ]
then
    tmux -2 new-session -d -s ${SESS_NAME}
    tmux split-window -h
    tmux split-window -v
    tmux select-pane -t 0
    # Battery
    tmux new-window -t ${SESS_NAME} -a -n Battery # -a: next index
    tmux send-keys -t ${SESS_NAME}:2 'watch_power' Enter
    # Finalise
    tmux select-window -t ${SESSION}:1
fi

tmux -2 attach -t ${SESS_NAME}
