#!/bin/bash

rofi -no-lazy-grab -show window \
	-hide-scrollbar true \
	-lines 11 \
	-line-padding 20 \
	-border-raduis 30 \
	-width 28 \
	-columns 1 \
	-show-icons -icon-theme "Papirus" \
	-font "Noto Sans 19"
